// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_U_rmJFLdSWSFhOom3LimXEXynkWNys',
    appId: '1:770172051049:web:e8a8a35631f3b7e7694cf8',
    messagingSenderId: '770172051049',
    projectId: 'notificationsender-43b71',
    authDomain: 'notificationsender-43b71.firebaseapp.com',
    databaseURL: 'https://notificationsender-43b71-default-rtdb.firebaseio.com',
    storageBucket: 'notificationsender-43b71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNGVucLRYCAVrdGeQBuTA78Rv90fxiik',
    appId: '1:770172051049:android:225afa57df6e63d9694cf8',
    messagingSenderId: '770172051049',
    projectId: 'notificationsender-43b71',
    databaseURL: 'https://notificationsender-43b71-default-rtdb.firebaseio.com',
    storageBucket: 'notificationsender-43b71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAqUWQCB9d035UW3FxKzA8ilSgx5F4k8Y',
    appId: '1:770172051049:ios:99e795464966d2d4694cf8',
    messagingSenderId: '770172051049',
    projectId: 'notificationsender-43b71',
    databaseURL: 'https://notificationsender-43b71-default-rtdb.firebaseio.com',
    storageBucket: 'notificationsender-43b71.appspot.com',
    iosClientId: '770172051049-pkhfhp6100qlkrkeldv9e4tdl2sq75fj.apps.googleusercontent.com',
    iosBundleId: 'com.sender.notification.notificationSender',
  );
}
